# --- AUTO-GENERATED CODE - DO NOT EDIT MANUALLY ---
# Generated by generate_commands.py
import logging
from typing import Any, Optional, Dict, List
from src.services.commands.base_command import BaseCommand
from src.models.application_model import ApplicationModel
from src.models.nodes.scene_node import SceneNode
from src.shared.events import Events
from src.services.event_aggregator import EventAggregator

logger = logging.getLogger(__name__)


# --- METADATA COMMANDS ---

class RenameNodeCommand(BaseCommand):
    """Generated command for RenameNode intent (Property Atom)."""
    def __init__(self, node: SceneNode, value: Any, event_aggregator: EventAggregator):
        super().__init__("RenameNode", event_aggregator)
        self.node = node
        pass
        self.new_value = value
        self.path = f"name"
        self.old_value = None

    def execute(self):
        concrete_path = self.path
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing RenameNode: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_RENAMED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path
        self.logger.debug(f"Undoing RenameNode: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_RENAMED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetNodeVisibilityCommand(BaseCommand):
    """Generated command for SetNodeVisibility intent (Property Atom)."""
    def __init__(self, node: SceneNode, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetNodeVisibility", event_aggregator)
        self.node = node
        pass
        self.new_value = value
        self.path = f"visible"
        self.old_value = None

    def execute(self):
        concrete_path = self.path
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetNodeVisibility: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_VISIBILITY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path
        self.logger.debug(f"Undoing SetNodeVisibility: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_VISIBILITY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetNodeLockedCommand(BaseCommand):
    """Generated command for SetNodeLocked intent (Property Atom)."""
    def __init__(self, node: SceneNode, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetNodeLocked", event_aggregator)
        self.node = node
        pass
        self.new_value = value
        self.path = f"locked"
        self.old_value = None

    def execute(self):
        concrete_path = self.path
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetNodeLocked: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_LOCKED_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path
        self.logger.debug(f"Undoing SetNodeLocked: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_LOCKED_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


# --- STRUCTURE COMMANDS ---

class AddNodeCommand(BaseCommand):
    """Generated command for AddNode intent (Tree Atom)."""
    def __init__(self, model: ApplicationModel, node: SceneNode, parent_id: str, event_aggregator: EventAggregator):
        super().__init__("AddNode", event_aggregator)
        self.model = model
        self.node = node
        self.parent_id = parent_id
        self.memento: Any = None # For capturing structural state

    def execute(self):
        self.logger.debug(f"Executing Tree Operation: AddNode")
        self.memento = self.model.insert_node(self.node, self.parent_id)
        self._event_aggregator.publish(Events.SCENE_GRAPH_CHANGED)

    def undo(self):
        self.logger.debug(f"Undoing Tree Operation: AddNode")
        self.model.undo_insert_node(self.memento)
        self._event_aggregator.publish(Events.SCENE_GRAPH_CHANGED)


class RemoveNodeCommand(BaseCommand):
    """Generated command for RemoveNode intent (Tree Atom)."""
    def __init__(self, model: ApplicationModel, node_id: str, event_aggregator: EventAggregator):
        super().__init__("RemoveNode", event_aggregator)
        self.model = model
        self.node_id = node_id
        self.memento: Any = None # For capturing structural state

    def execute(self):
        self.logger.debug(f"Executing Tree Operation: RemoveNode")
        self.memento = self.model.remove_node(self.node_id)
        self._event_aggregator.publish(Events.SCENE_GRAPH_CHANGED)

    def undo(self):
        self.logger.debug(f"Undoing Tree Operation: RemoveNode")
        self.model.undo_remove_node(self.memento)
        self._event_aggregator.publish(Events.SCENE_GRAPH_CHANGED)


class ReorderNodeCommand(BaseCommand):
    """Generated command for ReorderNode intent (Tree Atom)."""
    def __init__(self, model: ApplicationModel, node_id: str, event_aggregator: EventAggregator):
        super().__init__("ReorderNode", event_aggregator)
        self.model = model
        self.node_id = node_id
        self.memento: Any = None # For capturing structural state

    def execute(self):
        self.logger.debug(f"Executing Tree Operation: ReorderNode")
        self.memento = self.model.move_node(self.node_id)
        self._event_aggregator.publish(Events.NODE_ORDER_CHANGED_IN_SCENE)

    def undo(self):
        self.logger.debug(f"Undoing Tree Operation: ReorderNode")
        self.model.undo_move_node(self.memento)
        self._event_aggregator.publish(Events.NODE_ORDER_CHANGED_IN_SCENE)


class GroupNodesCommand(BaseCommand):
    """Generated command for GroupNodes intent (Composite Transaction)."""
    def __init__(self, node: SceneNode, event_aggregator: EventAggregator):
        super().__init__("GroupNodes", event_aggregator)
        self.sub_commands: List[BaseCommand] = [
            
        ]

    def execute(self):
        self.logger.debug(f"Executing Composite Transaction: GroupNodes")
        for cmd in self.sub_commands:
            cmd.execute()
        self._event_aggregator.publish(Events.SCENE_GRAPH_CHANGED)

    def undo(self):
        self.logger.debug(f"Undoing Composite Transaction: GroupNodes")
        for cmd in reversed(self.sub_commands):
            cmd.undo()
        self._event_aggregator.publish(Events.SCENE_GRAPH_CHANGED)


class UngroupNodesCommand(BaseCommand):
    """Generated command for UngroupNodes intent (Composite Transaction)."""
    def __init__(self, node: SceneNode, event_aggregator: EventAggregator):
        super().__init__("UngroupNodes", event_aggregator)
        self.sub_commands: List[BaseCommand] = [
            
        ]

    def execute(self):
        self.logger.debug(f"Executing Composite Transaction: UngroupNodes")
        for cmd in self.sub_commands:
            cmd.execute()
        self._event_aggregator.publish(Events.SCENE_GRAPH_CHANGED)

    def undo(self):
        self.logger.debug(f"Undoing Composite Transaction: UngroupNodes")
        for cmd in reversed(self.sub_commands):
            cmd.undo()
        self._event_aggregator.publish(Events.SCENE_GRAPH_CHANGED)


# --- STYLING COMMANDS ---

class SetPlotGeometryCommand(BaseCommand):
    """Generated command for SetPlotGeometry intent (Property Atom)."""
    def __init__(self, node: SceneNode, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetPlotGeometry", event_aggregator)
        self.node = node
        pass
        self.new_value = value
        self.path = f"plot_properties.geometry"
        self.old_value = None

    def execute(self):
        concrete_path = self.path
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetPlotGeometry: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path
        self.logger.debug(f"Undoing SetPlotGeometry: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetPlotTitleTextCommand(BaseCommand):
    """Generated command for SetPlotTitleText intent (Property Atom)."""
    def __init__(self, node: SceneNode, position: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetPlotTitleText", event_aggregator)
        self.node = node
        self.position = position
        self.new_value = value
        self.path = f"plot_properties.titles.{position}.text"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(position=self.position)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetPlotTitleText: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(position=self.position)
        self.logger.debug(f"Undoing SetPlotTitleText: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetPlotTitleFontCommand(BaseCommand):
    """Generated command for SetPlotTitleFont intent (Property Atom)."""
    def __init__(self, node: SceneNode, position: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetPlotTitleFont", event_aggregator)
        self.node = node
        self.position = position
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.titles.{position}.font.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(position=self.position, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetPlotTitleFont: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(position=self.position, property=self.property)
        self.logger.debug(f"Undoing SetPlotTitleFont: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetPlotTitleVisualsCommand(BaseCommand):
    """Generated command for SetPlotTitleVisuals intent (Property Atom)."""
    def __init__(self, node: SceneNode, position: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetPlotTitleVisuals", event_aggregator)
        self.node = node
        self.position = position
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.titles.{position}.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(position=self.position, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetPlotTitleVisuals: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(position=self.position, property=self.property)
        self.logger.debug(f"Undoing SetPlotTitleVisuals: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetAxisLabelTextCommand(BaseCommand):
    """Generated command for SetAxisLabelText intent (Property Atom)."""
    def __init__(self, node: SceneNode, axis: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetAxisLabelText", event_aggregator)
        self.node = node
        self.axis = axis
        self.new_value = value
        self.path = f"plot_properties.coords.{axis}.label.text"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(axis=self.axis)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetAxisLabelText: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(axis=self.axis)
        self.logger.debug(f"Undoing SetAxisLabelText: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetAxisLabelFontCommand(BaseCommand):
    """Generated command for SetAxisLabelFont intent (Property Atom)."""
    def __init__(self, node: SceneNode, axis: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetAxisLabelFont", event_aggregator)
        self.node = node
        self.axis = axis
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.coords.{axis}.label.font.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(axis=self.axis, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetAxisLabelFont: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(axis=self.axis, property=self.property)
        self.logger.debug(f"Undoing SetAxisLabelFont: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetAxisLabelVisualsCommand(BaseCommand):
    """Generated command for SetAxisLabelVisuals intent (Property Atom)."""
    def __init__(self, node: SceneNode, axis: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetAxisLabelVisuals", event_aggregator)
        self.node = node
        self.axis = axis
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.coords.{axis}.label.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(axis=self.axis, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetAxisLabelVisuals: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(axis=self.axis, property=self.property)
        self.logger.debug(f"Undoing SetAxisLabelVisuals: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetAxisLimitsCommand(BaseCommand):
    """Generated command for SetAxisLimits intent (Property Atom)."""
    def __init__(self, node: SceneNode, axis: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetAxisLimits", event_aggregator)
        self.node = node
        self.axis = axis
        self.new_value = value
        self.path = f"plot_properties.coords.{axis}.limits"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(axis=self.axis)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetAxisLimits: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(axis=self.axis)
        self.logger.debug(f"Undoing SetAxisLimits: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetAxisMarginCommand(BaseCommand):
    """Generated command for SetAxisMargin intent (Property Atom)."""
    def __init__(self, node: SceneNode, axis: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetAxisMargin", event_aggregator)
        self.node = node
        self.axis = axis
        self.new_value = value
        self.path = f"plot_properties.coords.{axis}.margin"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(axis=self.axis)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetAxisMargin: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(axis=self.axis)
        self.logger.debug(f"Undoing SetAxisMargin: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetAxisAutolimitModeCommand(BaseCommand):
    """Generated command for SetAxisAutolimitMode intent (Property Atom)."""
    def __init__(self, node: SceneNode, axis: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetAxisAutolimitMode", event_aggregator)
        self.node = node
        self.axis = axis
        self.new_value = value
        self.path = f"plot_properties.coords.{axis}.autolimit_mode"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(axis=self.axis)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetAxisAutolimitMode: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(axis=self.axis)
        self.logger.debug(f"Undoing SetAxisAutolimitMode: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetAxisScientificNotationCommand(BaseCommand):
    """Generated command for SetAxisScientificNotation intent (Property Atom)."""
    def __init__(self, node: SceneNode, axis: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetAxisScientificNotation", event_aggregator)
        self.node = node
        self.axis = axis
        self.new_value = value
        self.path = f"plot_properties.coords.{axis}.use_offset"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(axis=self.axis)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetAxisScientificNotation: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(axis=self.axis)
        self.logger.debug(f"Undoing SetAxisScientificNotation: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetTickParametersCommand(BaseCommand):
    """Generated command for SetTickParameters intent (Property Atom)."""
    def __init__(self, node: SceneNode, axis: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetTickParameters", event_aggregator)
        self.node = node
        self.axis = axis
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.coords.{axis}.ticks.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(axis=self.axis, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetTickParameters: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(axis=self.axis, property=self.property)
        self.logger.debug(f"Undoing SetTickParameters: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetSpineVisualsCommand(BaseCommand):
    """Generated command for SetSpineVisuals intent (Property Atom)."""
    def __init__(self, node: SceneNode, spine: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetSpineVisuals", event_aggregator)
        self.node = node
        self.spine = spine
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.coords.spines.{spine}.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(spine=self.spine, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetSpineVisuals: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(spine=self.spine, property=self.property)
        self.logger.debug(f"Undoing SetSpineVisuals: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetGridVisualsCommand(BaseCommand):
    """Generated command for SetGridVisuals intent (Property Atom)."""
    def __init__(self, node: SceneNode, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetGridVisuals", event_aggregator)
        self.node = node
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.coords.grid.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetGridVisuals: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(property=self.property)
        self.logger.debug(f"Undoing SetGridVisuals: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetPlotFacecolorCommand(BaseCommand):
    """Generated command for SetPlotFacecolor intent (Property Atom)."""
    def __init__(self, node: SceneNode, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetPlotFacecolor", event_aggregator)
        self.node = node
        pass
        self.new_value = value
        self.path = f"plot_properties.coords.facecolor"
        self.old_value = None

    def execute(self):
        concrete_path = self.path
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetPlotFacecolor: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path
        self.logger.debug(f"Undoing SetPlotFacecolor: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetArtistVisibilityCommand(BaseCommand):
    """Generated command for SetArtistVisibility intent (Property Atom)."""
    def __init__(self, node: SceneNode, index: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetArtistVisibility", event_aggregator)
        self.node = node
        self.index = index
        self.new_value = value
        self.path = f"plot_properties.artists.{index}.visible"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(index=self.index)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetArtistVisibility: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(index=self.index)
        self.logger.debug(f"Undoing SetArtistVisibility: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetArtistZOrderCommand(BaseCommand):
    """Generated command for SetArtistZOrder intent (Property Atom)."""
    def __init__(self, node: SceneNode, index: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetArtistZOrder", event_aggregator)
        self.node = node
        self.index = index
        self.new_value = value
        self.path = f"plot_properties.artists.{index}.zorder"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(index=self.index)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetArtistZOrder: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(index=self.index)
        self.logger.debug(f"Undoing SetArtistZOrder: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetArtistDataMappingCommand(BaseCommand):
    """Generated command for SetArtistDataMapping intent (Property Atom)."""
    def __init__(self, node: SceneNode, index: Any, axis: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetArtistDataMapping", event_aggregator)
        self.node = node
        self.index = index
        self.axis = axis
        self.new_value = value
        self.path = f"plot_properties.artists.{index}.{axis}_column"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(index=self.index, axis=self.axis)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetArtistDataMapping: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(index=self.index, axis=self.axis)
        self.logger.debug(f"Undoing SetArtistDataMapping: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetArtistVisualsCommand(BaseCommand):
    """Generated command for SetArtistVisuals intent (Property Atom)."""
    def __init__(self, node: SceneNode, index: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetArtistVisuals", event_aggregator)
        self.node = node
        self.index = index
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.artists.{index}.visuals.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetArtistVisuals: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.logger.debug(f"Undoing SetArtistVisuals: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetPatchVisualsCommand(BaseCommand):
    """Generated command for SetPatchVisuals intent (Property Atom)."""
    def __init__(self, node: SceneNode, index: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetPatchVisuals", event_aggregator)
        self.node = node
        self.index = index
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.artists.{index}.visuals.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetPatchVisuals: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.logger.debug(f"Undoing SetPatchVisuals: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetMappableVisualsCommand(BaseCommand):
    """Generated command for SetMappableVisuals intent (Property Atom)."""
    def __init__(self, node: SceneNode, index: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetMappableVisuals", event_aggregator)
        self.node = node
        self.index = index
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.artists.{index}.visuals.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetMappableVisuals: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.logger.debug(f"Undoing SetMappableVisuals: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetContourParametersCommand(BaseCommand):
    """Generated command for SetContourParameters intent (Property Atom)."""
    def __init__(self, node: SceneNode, index: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetContourParameters", event_aggregator)
        self.node = node
        self.index = index
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.artists.{index}.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetContourParameters: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.logger.debug(f"Undoing SetContourParameters: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetHistogramParametersCommand(BaseCommand):
    """Generated command for SetHistogramParameters intent (Property Atom)."""
    def __init__(self, node: SceneNode, index: Any, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetHistogramParameters", event_aggregator)
        self.node = node
        self.index = index
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.artists.{index}.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetHistogramParameters: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(index=self.index, property=self.property)
        self.logger.debug(f"Undoing SetHistogramParameters: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class SetGlobalVisualsCommand(BaseCommand):
    """Generated command for SetGlobalVisuals intent (Property Atom)."""
    def __init__(self, node: SceneNode, property: Any, value: Any, event_aggregator: EventAggregator):
        super().__init__("SetGlobalVisuals", event_aggregator)
        self.node = node
        self.property = property
        self.new_value = value
        self.path = f"plot_properties.artists.*.visuals.{property}"
        self.old_value = None

    def execute(self):
        concrete_path = self.path.format(property=self.property)
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing SetGlobalVisuals: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path.format(property=self.property)
        self.logger.debug(f"Undoing SetGlobalVisuals: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


# --- DATA COMMANDS ---

class UpdateDataframeCommand(BaseCommand):
    """Generated command for UpdateDataframe intent (Property Atom)."""
    def __init__(self, node: SceneNode, value: Any, event_aggregator: EventAggregator):
        super().__init__("UpdateDataframe", event_aggregator)
        self.node = node
        pass
        self.new_value = value
        self.path = f"data.dataframe"
        self.old_value = None

    def execute(self):
        concrete_path = self.path
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing UpdateDataframe: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_DATA_LOADED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path
        self.logger.debug(f"Undoing UpdateDataframe: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_DATA_LOADED, node_id=target_id, path=concrete_path, value=self.old_value)


class UpdateDataPathCommand(BaseCommand):
    """Generated command for UpdateDataPath intent (Property Atom)."""
    def __init__(self, node: SceneNode, value: Any, event_aggregator: EventAggregator):
        super().__init__("UpdateDataPath", event_aggregator)
        self.node = node
        pass
        self.new_value = value
        self.path = f"data.file_path"
        self.old_value = None

    def execute(self):
        concrete_path = self.path
        self.old_value = self.get_value_by_path(self.node, concrete_path)
        self.logger.debug(f"Executing UpdateDataPath: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.node, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_DATA_FILE_PATH_UPDATED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path
        self.logger.debug(f"Undoing UpdateDataPath: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.node, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.node, "plot_properties"):
            self.node.plot_properties._version += 1
        target_id = getattr(self.node, "id", None)
        self._event_aggregator.publish(Events.NODE_DATA_FILE_PATH_UPDATED, node_id=target_id, path=concrete_path, value=self.old_value)


class LoadAndApplyDataCommand(BaseCommand):
    """Generated command for LoadAndApplyData intent (Composite Transaction)."""
    def __init__(self, node: SceneNode, col_x: Any, col_y: Any, df: Any, path: Any, event_aggregator: EventAggregator):
        super().__init__("LoadAndApplyData", event_aggregator)
        self.sub_commands: List[BaseCommand] = [
            UpdateDataPathCommand(node, path, event_aggregator),
            UpdateDataframeCommand(node, df, event_aggregator),
            SetArtistDataMappingCommand(node, 0, 'x', col_x, event_aggregator),
            SetArtistDataMappingCommand(node, 0, 'y', col_y, event_aggregator)
        ]

    def execute(self):
        self.logger.debug(f"Executing Composite Transaction: LoadAndApplyData")
        for cmd in self.sub_commands:
            cmd.execute()
        self._event_aggregator.publish(Events.NODE_DATA_LOADED)

    def undo(self):
        self.logger.debug(f"Undoing Composite Transaction: LoadAndApplyData")
        for cmd in reversed(self.sub_commands):
            cmd.undo()
        self._event_aggregator.publish(Events.NODE_DATA_LOADED)


# --- LAYOUT COMMANDS ---

class SwitchLayoutModeCommand(BaseCommand):
    """Generated command for SwitchLayoutMode intent (Property Atom)."""
    def __init__(self, model: ApplicationModel, value: Any, event_aggregator: EventAggregator):
        super().__init__("SwitchLayoutMode", event_aggregator)
        self.model = model
        pass
        self.new_value = value
        self.path = f"current_layout_config"
        self.old_value = None

    def execute(self):
        concrete_path = self.path
        self.old_value = self.get_value_by_path(self.model, concrete_path)
        self.logger.debug(f"Executing SwitchLayoutMode: {concrete_path} = {self.new_value} (was: {self.old_value})")
        self.set_value_by_path(self.model, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.model, "plot_properties"):
            self.model.plot_properties._version += 1
        target_id = getattr(self.model, "id", None)
        self._event_aggregator.publish(Events.ACTIVE_LAYOUT_MODE_CHANGED, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        concrete_path = self.path
        self.logger.debug(f"Undoing SwitchLayoutMode: {concrete_path} reverted to {self.old_value}")
        self.set_value_by_path(self.model, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.model, "plot_properties"):
            self.model.plot_properties._version += 1
        target_id = getattr(self.model, "id", None)
        self._event_aggregator.publish(Events.ACTIVE_LAYOUT_MODE_CHANGED, node_id=target_id, path=concrete_path, value=self.old_value)


class BatchAlignPlotsCommand(BaseCommand):
    """Generated command for BatchAlignPlots intent (Batch Atom)."""
    def __init__(self, model: ApplicationModel, values: Dict[str, Any], event_aggregator: EventAggregator):
        super().__init__("BatchAlignPlots", event_aggregator)
        self.model = model
        self.new_values = values
        self.path = "plot_properties.geometry"
        self.old_values: Dict[str, Any] = {}

    def execute(self):
        self.logger.debug(f"Executing Batch BatchAlignPlots on path '{self.path}'")
        for node_id, value in self.new_values.items():
            node = self.model.scene_root.find_node_by_id(node_id)
            if node:
                self.old_values[node_id] = self.get_value_by_path(node, self.path)
                self.set_value_by_path(node, self.path, value)
                if self.path.startswith("plot_properties") and hasattr(node, "plot_properties"):
                    node.plot_properties._version += 1
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED)

    def undo(self):
        self.logger.debug(f"Undoing Batch BatchAlignPlots")
        for node_id, old_value in self.old_values.items():
            node = self.model.scene_root.find_node_by_id(node_id)
            if node:
                self.set_value_by_path(node, self.path, old_value)
                if self.path.startswith("plot_properties") and hasattr(node, "plot_properties"):
                    node.plot_properties._version += 1
        self._event_aggregator.publish(Events.PLOT_PROPERTY_CHANGED)


class UpdateGridParametersCommand(BaseCommand):
    """Generated command for UpdateGridParameters intent (Composite Transaction)."""
    def __init__(self, model: ApplicationModel, new_config: Any, event_aggregator: EventAggregator):
        super().__init__("UpdateGridParameters", event_aggregator)
        self.sub_commands: List[BaseCommand] = [
            SwitchLayoutModeCommand(model, new_config, event_aggregator),
            BatchAlignPlotsCommand(model, 'layout_manager.calculate_grid', event_aggregator)
        ]

    def execute(self):
        self.logger.debug(f"Executing Composite Transaction: UpdateGridParameters")
        for cmd in self.sub_commands:
            cmd.execute()
        self._event_aggregator.publish(Events.LAYOUT_CONFIG_CHANGED)

    def undo(self):
        self.logger.debug(f"Undoing Composite Transaction: UpdateGridParameters")
        for cmd in reversed(self.sub_commands):
            cmd.undo()
        self._event_aggregator.publish(Events.LAYOUT_CONFIG_CHANGED)


class ApplyLayoutTemplateCommand(BaseCommand):
    """Generated command for ApplyLayoutTemplate intent (Composite Transaction)."""
    def __init__(self, model: ApplicationModel, event_aggregator: EventAggregator):
        super().__init__("ApplyLayoutTemplate", event_aggregator)
        self.sub_commands: List[BaseCommand] = [
            
        ]

    def execute(self):
        self.logger.debug(f"Executing Composite Transaction: ApplyLayoutTemplate")
        for cmd in self.sub_commands:
            cmd.execute()
        self._event_aggregator.publish(Events.PROJECT_WAS_RESET)

    def undo(self):
        self.logger.debug(f"Undoing Composite Transaction: ApplyLayoutTemplate")
        for cmd in reversed(self.sub_commands):
            cmd.undo()
        self._event_aggregator.publish(Events.PROJECT_WAS_RESET)
