import json
import re
from pathlib import Path

MANIFEST_PATH = Path(__file__).parent / "command_manifest.json"
OUTPUT_PATH = Path(__file__).parent / "commands.py"

HEADER = """# --- AUTO-GENERATED CODE - DO NOT EDIT MANUALLY ---
# Generated by generate_commands.py
import logging
from typing import Any, Optional, Dict, List
from src.services.commands.base_command import BaseCommand
from src.models.application_model import ApplicationModel
from src.models.nodes.scene_node import SceneNode
from src.models.nodes.plot_node import PlotNode
from src.shared.events import Events
from src.services.event_aggregator import EventAggregator

logger = logging.getLogger(__name__)
"""

def to_snake_case(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

# Archetype 1: Property Update (Single value)
UPDATE_TEMPLATE = """
class {name}Command(BaseCommand):
    \"\"\"Generated command for {name} intent (Property Atom).\"\"\"
    def __init__(self, {target_var}: {target_type}, {args}value: Any, event_aggregator: EventAggregator):
        super().__init__("{name}", event_aggregator)
        self.{target_var} = {target_var}
        {assignments}
        self.new_value = value
        self.path = f"{path}"
        self.old_value = None

    def execute(self):
        {path_resolution}
        self.old_value = self.get_value_by_path(self.{target_var}, concrete_path)
        self.logger.debug(f"Executing {name}: {{concrete_path}} = {{self.new_value}} (was: {{self.old_value}})")
        self.set_value_by_path(self.{target_var}, concrete_path, self.new_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.{target_var}, "plot_properties"):
            self.{target_var}.plot_properties._version += 1
        target_id = getattr(self.{target_var}, "id", None)
        self._event_aggregator.publish(Events.{event}, node_id=target_id, path=concrete_path, value=self.new_value)

    def undo(self):
        {path_resolution}
        self.logger.debug(f"Undoing {name}: {{concrete_path}} reverted to {{self.old_value}}")
        self.set_value_by_path(self.{target_var}, concrete_path, self.old_value)
        if concrete_path.startswith("plot_properties") and hasattr(self.{target_var}, "plot_properties"):
            self.{target_var}.plot_properties._version += 1
        target_id = getattr(self.{target_var}, "id", None)
        self._event_aggregator.publish(Events.{event}, node_id=target_id, path=concrete_path, value=self.old_value)
"""

# Archetype 2: Batch Update (Dict of {id: value})
BATCH_UPDATE_TEMPLATE = """
class {name}Command(BaseCommand):
    \"\"\"Generated command for {name} intent (Batch Atom).\"\"\"
    def __init__(self, {target_var}: {target_type}, values: Dict[str, Any], event_aggregator: EventAggregator):
        super().__init__("{name}", event_aggregator)
        self.{target_var} = {target_var}
        self.new_values = values
        self.path = "{path}"
        self.old_values: Dict[str, Any] = {{}}

    def execute(self):
        self.logger.debug(f"Executing Batch {name} on path '{{self.path}}'")
        # Assuming model-wide lookup for batch updates
        for node_id, value in self.new_values.items():
            node = self.{target_var}.scene_root.find_node_by_id(node_id)
            if node:
                self.old_values[node_id] = self.get_value_by_path(node, self.path)
                self.set_value_by_path(node, self.path, value)
                if self.path.startswith("plot_properties") and hasattr(node, "plot_properties"):
                    node.plot_properties._version += 1
        self._event_aggregator.publish(Events.{event})

    def undo(self):
        self.logger.debug(f"Undoing Batch {name}")
        for node_id, old_value in self.old_values.items():
            node = self.{target_var}.scene_root.find_node_by_id(node_id)
            if node:
                self.set_value_by_path(node, self.path, old_value)
                if self.path.startswith("plot_properties") and hasattr(node, "plot_properties"):
                    node.plot_properties._version += 1
        self._event_aggregator.publish(Events.{event})
"""

# Archetype 3: Tree Mutation (Insert/Remove/Move)
TREE_TEMPLATE = """
class {name}Command(BaseCommand):
    \"\"\"Generated command for {name} intent (Tree Atom).\"\"\"
    def __init__(self, {target_var}: {target_type}, {args}event_aggregator: EventAggregator):
        super().__init__("{name}", event_aggregator)
        self.{target_var} = {target_var}
        {assignments}
        self.memento: Any = None

    def execute(self):
        self.logger.debug(f"Executing Tree Operation: {name}")
        self.memento = self.{target_var}.{operation}({op_args})
        self._event_aggregator.publish(Events.{event})

    def undo(self):
        self.logger.debug(f"Undoing Tree Operation: {name}")
        self.{target_var}.undo_{operation}(self.memento)
        self._event_aggregator.publish(Events.{event})
"""

# Archetype 4: Composite (Transaction)
COMPOSITE_TEMPLATE = """
class {name}Command(BaseCommand):
    \"\"\"Generated command for {name} intent (Composite Transaction).\"\"\"
    def __init__(self, {target_var}: {target_type}, {args}event_aggregator: EventAggregator):
        super().__init__("{name}", event_aggregator)
        self.{target_var} = {target_var}
        {assignments}
        self.sub_commands: List[BaseCommand] = [
            {instantiations}
        ]

    def execute(self):
        self.logger.debug(f"Executing Composite Transaction: {name}")
        for cmd in self.sub_commands:
            cmd.execute()
        self._event_aggregator.publish(Events.{event})

    def undo(self):
        self.logger.debug(f"Undoing Composite Transaction: {name}")
        for cmd in reversed(self.sub_commands):
            cmd.undo()
        self._event_aggregator.publish(Events.{event})
"""

def get_placeholders(text):
    if not isinstance(text, str): return []
    return re.findall(r"\{(.*?)\}", text)

def generate():
    if not MANIFEST_PATH.exists():
        print(f"Error: Manifest not found at {MANIFEST_PATH}")
        return

    with open(MANIFEST_PATH, "r") as f:
        manifest = json.load(f)

    # Pre-parse all commands to map names to their targets for composite resolution
    COMMAND_TARGETS = {}
    for category, commands in manifest.items():
        for name, config in commands.items():
            target = config.get("target")
            if not target:
                raise ValueError(f"Command '{name}' in category '{category}' is missing a 'target' field.")
            COMMAND_TARGETS[name] = target

    code = [HEADER]

    for category, commands in manifest.items():
        code.append(f"\n# --- {category.upper()} COMMANDS ---")
        for name, config in commands.items():
            atom = config.get("atom")
            event = config.get("event")
            target_type = config["target"]
            target_var = to_snake_case(target_type)
            
            if atom == "update":
                path = config.get("path")
                interp_args = [p for p in get_placeholders(path) if p != "*"]
                args_str = "".join([f"{a}: Any, " for a in interp_args])
                assignments_str = "\n        ".join([f"self.{a} = {a}" for a in interp_args]) or "pass"
                
                if interp_args:
                    format_args_str = ", ".join([f"{a}=self.{a}" for a in interp_args])
                    path_resolution = f"concrete_path = self.path.format({format_args_str})"
                else:
                    path_resolution = "concrete_path = self.path"
                
                code.append(UPDATE_TEMPLATE.format(
                    name=name, path=path, event=event, target_var=target_var,
                    target_type=target_type, args=args_str, assignments=assignments_str,
                    path_resolution=path_resolution
                ))

            elif atom == "update_batch":
                path = config.get("path")
                code.append(BATCH_UPDATE_TEMPLATE.format(
                    name=name, path=path, event=event, 
                    target_var=target_var, target_type=target_type
                ))

            elif atom in ["insert", "remove", "move"]:
                op_map = {"insert": "insert_node", "remove": "remove_node", "move": "move_node"}
                operation = op_map[atom]
                args_str = "node_id: str, " if atom != "insert" else "node: SceneNode, parent_id: str, "
                assignments_str = f"self.node_id = node_id" if atom != "insert" else f"self.node = node\n        self.parent_id = parent_id"
                op_args = "self.node_id" if atom != "insert" else "self.node, self.parent_id"
                
                code.append(TREE_TEMPLATE.format(
                    name=name, operation=operation, event=event, args=args_str,
                    assignments=assignments_str, op_args=op_args,
                    target_var=target_var, target_type=target_type
                ))

            elif atom == "composite":
                steps = config.get("steps", [])
                all_placeholders = []
                instantiations = []

                for step in steps:
                    cmd_name = step.get("command")
                    if not cmd_name: continue
                    
                    sub_target_type = COMMAND_TARGETS.get(cmd_name)
                    sub_target_var = to_snake_case(sub_target_type)
                    
                    step_placeholders = []
                    for val in step.values():
                        step_placeholders.extend(get_placeholders(str(val)))
                    all_placeholders.extend(step_placeholders)
                    
                    # Logic: If composite target matches sub-command target, pass it through
                    # If not (e.g. model-based composite calling node-based command), we have a logical gap
                    # For now, we assume targets are compatible or available on the primary target
                    args_list = [target_var if sub_target_type == target_type else "FIXME_INCOMPATIBLE_TARGET"]
                    
                    for key, val in step.items():
                        if key == "command": continue
                        if str(val).startswith("{") and str(val).endswith("}"):
                            args_list.append(get_placeholders(str(val))[0])
                        else:
                            args_list.append(repr(val))
                    args_list.append("event_aggregator")
                    instantiations.append(f"{cmd_name}Command({', '.join(args_list)})")

                unique_placeholders = sorted(list(set(all_placeholders)))
                args_str = "".join([f"{p}: Any, " for p in unique_placeholders])
                assignments_str = "\n        ".join([f"self.{p} = {p}" for p in unique_placeholders]) or "pass"
                instantiation_str = ",\n            ".join(instantiations)

                code.append(COMPOSITE_TEMPLATE.format(
                    name=name, event=event, args=args_str, 
                    assignments=assignments_str, instantiations=instantiation_str,
                    target_var=target_var, target_type=target_type
                ))

    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(code))
    
    print(f"Successfully generated {OUTPUT_PATH}")

if __name__ == "__main__":
    generate()
