themes:
  dark:
    style: "Fusion"
    palette:
      Window: [53, 53, 53]
      WindowText: [255, 255, 255]
      Base: [25, 25, 25]
      AlternateBase: [53, 53, 53]
      ToolTipBase: [255, 255, 255]
      ToolTipText: [255, 255, 255]
      Text: [255, 255, 255]
      Button: [53, 53, 53]
      ButtonText: [255, 255, 255]
      BrightText: [255, 0, 0]
      Link: [42, 130, 218]
      Highlight: [42, 130, 218]
      HighlightedText: [0, 0, 0]
      PlaceholderText: [160, 160, 160]
    stylesheet: |
      QTabWidget::pane {
          border-top: 1px solid #3d3d3d;
          border-bottom: 1px solid #3d3d3d;
          background-color: #2b2b2b;
      }
      QWidget#RibbonTabPage {
          background-color: #2b2b2b;
      }
      QScrollArea {
          border: none;
          background-color: #2b2b2b;
      }
      QToolButton {
          background-color: transparent;
          color: #e3e3e3;
          border: 1px solid transparent;
          border-radius: 2px;
          font-size: 10px;
          padding: 2px;
      }
      QToolButton:hover {
          background-color: #3d3d3d;
          border: 1px solid #4d4d4d;
      }
      QMenuBar#IntegratedMenuBar {
          background-color: transparent;
          border: none;
          color: #e3e3e3;
          padding-left: 5px;
      }
      QMenuBar#IntegratedMenuBar::item {
          background: transparent;
          padding: 4px 10px;
          border-radius: 4px;
          margin-top: 4px;
          margin-bottom: 4px;
      }
      QMenuBar#IntegratedMenuBar::item:selected {
          background-color: #3d3d3d;
      }
      QMenuBar#IntegratedMenuBar::item:pressed {
          background-color: #4d4d4d;
      }
  light:
    style: "Fusion"
    palette:
      Window: [240, 240, 240]
      WindowText: [0, 0, 0]
      Base: [255, 255, 255]
      AlternateBase: [220, 220, 220]
      ToolTipBase: [255, 255, 220]
      ToolTipText: [0, 0, 0]
      Text: [0, 0, 0]
      Button: [240, 240, 240]
      ButtonText: [0, 0, 0]
      BrightText: [255, 0, 0]
      Link: [0, 0, 238]
      Highlight: [51, 153, 255]
      HighlightedText: [255, 255, 255]
      PlaceholderText: [128, 128, 128]
